#!/usr/bin/env perl
use strict;

use Mojo::Base -strict;
use Mojolicious::Commands;

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

# Application
$ENV{MOJO_APP} ||= 'NephologyServer';

# Start commands
Mojolicious::Commands->start;
